### ISSUE TITLE
Sample unit test module for Login

### ISSUE THREAD

**Issue by Periyasamy025** [luka-zitnik/CodeIgniterModule#6]
Hi can you please tell me the Sample unit test module for Login using your Codeception CodeIgniterModule

Thank you

**Comment by luka-zitnik** [comment]
https://github.com/luka-zitnik/CodeIgniterModule/blob/master/tests/functional/FormsCept.php

Are you looking for something like that?

It's a test for this module, but also a usage example. It shows you how to work with web forms in general.
